name:                terminal
synopsis:            Portable terminal interaction library
version:             0.1.0.0
github:              "lpeterse/haskell-terminal"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"
category:            Terminal

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/lpeterse/haskell-terminal#readme>

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- exceptions
- stm
- text
- transformers
- prettyprinter

library:
  ghc-options: -Wall -fwarn-incomplete-patterns
  exposed-modules:
    - Control.Monad.Terminal
    - System.Terminal
  other-modules:
    - Control.Monad.Terminal.Decoder
    - Control.Monad.Terminal.Input
    - Control.Monad.Terminal.Monad
    - Control.Monad.Terminal.Printer
    - Control.Monad.Terminal.Terminal
    - Control.Monad.Terminal.TerminalT
    - System.Terminal.Platform
  source-dirs: src
  when:
    - condition: os(windows)
      then:
        source-dirs:
          - platform/windows/src
        include-dirs:
          - platform/windows/include
        c-sources:
          - platform/windows/cbits/hs_terminal.c
      else:
        source-dirs:
          - platform/posix/src
        include-dirs:
          - platform/posix/include
        c-sources:
          - platform/posix/cbits/hs_terminal.c

tests:
  terminal-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
    - tasty
    - tasty-hunit
    - tasty-quickcheck

#executables:
#  terminal-ev:
#    main:                Main.hs
#    source-dirs:         app/terminal-ev
#    ghc-options:
#    - -Werror
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - terminal
#  terminal-out:
#    main:                Main.hs
#    source-dirs:         app/terminal-out
#    ghc-options:
#    - -Werror
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - terminal
